// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;
using TCCApi.EventoApi.Dados;

namespace TCCApi.EventoApi.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20180901141952_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("TCCApi.EventoApi.Models.DTO.EventoDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro");

                    b.Property<string>("Cep");

                    b.Property<string>("Cidade");

                    b.Property<string>("Complemento");

                    b.Property<DateTime>("DataAtualizacao");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<DateTime>("DataEvento");

                    b.Property<DateTime>("DataFimInscricao");

                    b.Property<string>("Descricao");

                    b.Property<string>("DescricaoSimples");

                    b.Property<string>("EmpresaNome");

                    b.Property<int?>("IdEmpresa");

                    b.Property<string>("Logradouro");

                    b.Property<string>("Nome");

                    b.Property<string>("Numero");

                    b.Property<string>("PublicoAlvo");

                    b.Property<string>("UF");

                    b.Property<double>("Valor");

                    b.HasKey("Id");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("TCCApi.EventoApi.Models.DTO.EventoTagDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("EventoDTOId");

                    b.Property<string>("TagName");

                    b.HasKey("Id");

                    b.HasIndex("EventoDTOId");

                    b.ToTable("EventoTagDTO");
                });

            modelBuilder.Entity("TCCApi.EventoApi.Models.DTO.EventoTagDTO", b =>
                {
                    b.HasOne("TCCApi.EventoApi.Models.DTO.EventoDTO")
                        .WithMany("Tags")
                        .HasForeignKey("EventoDTOId");
                });
#pragma warning restore 612, 618
        }
    }
}
